### ISSUE TITLE
Fail to convert

### ISSUE THREAD

**Issue by wenching33** [daquexian/DNNConvertTool#5]
Hi, I downloaded squeezenet caffe model from https://github.com/DeepScale/SqueezeNet, and 
Try to convert it to .daq model following the instructions you wrote.
But the transformation terminated with error message "core dumped"
Below is the last rows of printed message.

Is there any way I can check where the cause is ?
Thanks.

PS. I use Ubuntu 16.04LTS, python3.5, and Caffe has been successfully installed.
      No GPU is in my notebook, I use CPU only.

---
I0518 15:20:05.292441 10474 net.cpp:242] This network produces output prob
I0518 15:20:05.292491 10474 net.cpp:255] Network initialization done.
I0518 15:20:05.296623 10474 net.cpp:744] Ignoring source layer label_data_1_split
I0518 15:20:05.297698 10474 net.cpp:744] Ignoring source layer pool10_pool10_0_split
I0518 15:20:05.297741 10474 net.cpp:744] Ignoring source layer loss
I0518 15:20:05.297746 10474 net.cpp:744] Ignoring source layer accuracy
I0518 15:20:05.297750 10474 net.cpp:744] Ignoring source layer accuracy_top5
程式記憶體區段錯誤 (core dumped)

**Comment by daquexian** [comment]
Thanks for your report. I will try to reproduce it on my side tomorrow. I'm not at home today

**Comment by daquexian** [comment]
Hmm, I remember I just tried squeezenet after my last commit and it works fine. You might want to add some logs in `dnntools/caffe_converter/caffe2daq.py` to find which layer causes the crash.

**Comment by wenching33** [comment]
Got it, Thanks for your response. I will try it first.

**Comment by wenching33** [comment]
Below is the message copy from my console. Is it normal that "deprecated use of Python interface" shows ?


-----
wenching@wenching-PORTEGE-R830:~/caffePrac/dnnConvert$ cat convSquNet.py 
import dnntools.caffe_converter
dnntools.caffe_converter.convert('squeezenet/deploy.prototxt',
                                 'squeezenet/squeezenet_v1.1.caffemodel',
                                 'squeezenet/squeezenet.daq')
wenching@wenching-PORTEGE-R830:~/caffePrac/dnnConvert$ python3 convSquNet.py 
WARNING: Logging before InitGoogleLogging() is written to STDERR
W0518 16:08:33.385999 11392 _caffe.cpp:139] DEPRECATION WARNING - deprecated use of Python interface
W0518 16:08:33.386036 11392 _caffe.cpp:140] Use this instead (with the named "weights" parameter):
W0518 16:08:33.386054 11392 _caffe.cpp:142] Net('squeezenet/deploy.prototxt', 1, weights='squeezenet/squeezenet_v1.1.caffemodel')
I0518 16:08:33.387842 11392 net.cpp:51] Initializing net from parameters:

**Comment by daquexian** [comment]
Yes, it is normal

**Comment by wenching33** [comment]
I found it crashed at line 102 in caffe_converter.py at second layer 'conv1'
Any idea the cause?  
Thanks!
---
101                 print(layer.name)
102                 weights = net.params[layer.name][0].data
103                 swapped_weights = np.moveaxis(weights, 1, 3)

**Comment by daquexian** [comment]
Could you check whether your caffemodel is corrupted?

**Comment by wenching33** [comment]
I think it should be ok. Because I just downloaded it on the github, and I have use it in another demo app. That app just worked fine. 
I found that
"net = caffe.Net(prototxt, caffemodel, caffe.TEST)"
and caffe is imported.
Maybe there was something wrong when I compiled pycaffe.
Anyway. Thanks for your help.

**Comment by wenching33** [comment]
Update:
I finally found the root cause. It should be the protobuf version problem.
After I tried: 
pip3 install --user --upgrade protobuf==3.1.0.post1
(Found at: https://github.com/BVLC/caffe/issues/5357)
The transformation succeeds.

**Comment by daquexian** [comment]
@wenching33 Thanks! I have updated setup.py to satisfy this requirement.

**Comment by daquexian** [comment]
Close via 0dac68a

**Comment by daquexian** [comment]
Hmm.. It seems the protobuf version problem is not common. The program crashed after I downgraded to 3.1.0.post1. I have reverted the commit 😂 .

To users who have this problem, you can downgrade protobuf by yourself.

**Comment by daquexian** [comment]
I have updated README.md for this issue in 0aba162.
